.TH GTASKS2ICAL 1 "September 27th, 2012" "Ole Wolf"

.SH NAME
gtasks2ical \- Conversion between Google Tasks and iCalendar format.

.SH SYNOPSIS

.B gtasks2ical
.RI [ options ]
.IR \fR[\fIregexp\fR]
.IR directory\fR|\fIfile

.SH DESCRIPTION
.B gtasks2ical
connects to a Google account and converts the user's Google Tasks to either one multi-task iCalendar format file or one iCalendar file for each task, or vice versa.

The standard form of the
.B gtasks2ical
command is

.RS
\fC\fBgtasks2ical
.RI [ options ]
.RI [ regexp ]
.IR directory\fR|\fIfile

.RE
This attempts to synchronize the Google Tasks with the tasks in the local file(s). Any Google Task that is newer than the corresponding task in the local file will be downloaded and written to the local file; and any task in a local file that is newer than the corresponding Google Task will be uploaded to Google.

The Google Tasks are synchronized with a single file with multiple tasks if
.I directory\fR|\fIfile
specifies a file; otherwise a file for each Google Task is created in the specified directory.

.B tasks2ical
uses the default Google Task list if
.I regexp
is omitted. Otherwise
.I regexp
is a regular expression that specifies which Google Tasks lists should be used for the conversion.
.B tasks2ical
will produce local iCalendar files for each list. (This behavior is currently subject to change.)


.SH OPTIONS

.TP
.PD 0
.B \-d
.TP
.PD
.B \-\-download
Force a download from Google Task, overwriting the local file even if the local file is newer. By combining the option with the
.I --task
option, a specific task may be selected for download, keeping the remaining tasks in the local file intact.


.TP
.PD 0
.B \-u
.TP
.PD
.B \-\-upload
Force a upload to Google Tasks, overwriting the Google Tasks if they are newer. By combining the option with the
.I --task
option, a specific task may be selected for upload, keeping the remaining Google tasks intact.


.TP
.PD 0
.B \-t \fIEID
.TP
.PD
.B \-\-task=\fIEID
Specify that only the task with the specified EID should be considered for synchronization. The
.I --task
option may be specified multiple times, allowing multiple tasks to be synchronized while keeping the remaining tasks intact.


.TP
.PD 0
.B \-h
.TP
.PD
.B \-\-help
Print help for
.B gtasks2ical
and exit.


.TP
.PD 0
.B \-L
.TP
.PD
.B \-\-license
Print licensing information for
.B gtasks2ical
and exit.


.TP
.PD 0
.B \-v
.TP
.PD
.B \-\-verbose
Print verbose output.


.TP
.PD 0
.B \-V
.TP
.PD
.B \-\-version
Print the version of
.B gtasks2ical
and exit.


.SH COPYRIGHT

gtasks2ical is Copyright (C) 2012 Ole Wolf

This program comes with ABSOLUTELY NO WARRANTY. This is free software, and you
are welcome to redistribute it under the conditions of the GNU General Public
License. See <http://www.gnu.org/licenses/> for details.
