.TH GTASKS2ICAL 1 "September 25nd, 2012" "Ole Wolf"

.SH NAME
gtasks2ical \- Conversion between Google Tasks and iCalendar format.

.SH SYNOPSIS

.B gtasks2ical
.RI [ options ]
.IR regexp

.SH DESCRIPTION
.B gtasks2ical
Does something

The standard form of the
.B gtasks2ical
command is

.RS
\fC\fBgtasks2ical\fR
.I regexp

.RE
This does something.


.SH OPTIONS

.TP
.PD 0
.B \-h
.TP
.PD
.B \-\-help
Print help for
.B gtasks2ical
and exit.


.TP
.PD 0
.B \-L
.TP
.PD
.B \-\-license
Print licensing information for
.B gtasks2ical
and exit.


.TP
.PD 0
.B \-v
.TP
.PD
.B \-\-verbose
Print verbose output.


.TP
.PD 0
.B \-V
.TP
.PD
.B \-\-version
Print the version of
.B gtasks2ical
and exit.


.SH COPYRIGHT

gtasks2ical is Copyright (C) 2012 Ole Wolf

This program comes with ABSOLUTELY NO WARRANTY. This is free software, and you
are welcome to redistribute it under the conditions of the GNU General Public
License. See <http://www.gnu.org/licenses/> for details.
